name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v2.4.0
      with:
        submodules: true
        
    - name: Setup Go
      uses: actions/setup-go@v2.1.5
      with:
        go-version: '1.17.6'

    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@v1.12.0
      env:
        HUGO_VERSION: 0.92.0
        HUGO_EXTENDED: true
        TARGET_REPO: m9brady/m9brady.github.io
        TOKEN: ${{ secrets.GHP_TOKEN }}
